#ifndef PWRINSPACE_CAN_COMMANDS_H
#define PWRINSPACE_CAN_COMMANDS_H

/** PLACE YOUR CAN CALLBACKS AND CAN MESSAGES HERE IN FORMAT*/
typedef enum {
  // RECIEVE
  CAN_GET_STATUS = 0x3DF0,
  CAN_GET_BOARD_DATA = 0x2DE0,
  CAN_GET_PRESS_DATA = 0x2DD0,
  CAN_GET_TEMP_DATA = 0x2DC0,
  CAN_SET_PRESS_DATA_RATE = 0x3DB0,
  CAN_GET_PRESS_INFO = 0x3DA0,
  // SEND
  CAN_SEND_BOARD_STATUS = 0x3DD0,
  CAN_SEND_BOARD_DATA = 0x3D00,
  CAN_SEND_PRESS_DATA_1 = 0x3D11,
  CAN_SEND_PRESS_DATA_2 = 0x3D12,
  CAN_SEND_TEMP_DATA = 0x3D20,
  CAN_SEND_PRESS_INFO = 0x3D30
} can_message_id_t;

/*PLACE YOUR FUNCTIONS ACCORDING TO THE TEMPLATE
 * typedef esp_err_t (*can_command_handler_t)(uint8_t *data, uint8_t length);
 *
 * REGISTER THEM IN can_config.c FILE
 */

#endif // PWRINSPACE_CAN_COMMANDS_H